version: '3'

services:
    app:
      image: 2kmiguel64/modular-chat:1.0.0
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - ./.env
      restart: always
      volumes:
        - .:/app
      ports:
        - ${PORT}:${PORT}
      container_name: modular-chat
      command: npm start